version: "3"
services:
  nginx:
    image: nginx:${NGINX_VERSION}
    ports:
      - "${NGINX_HTTP_HOST_PORT}:80"
      - "${NGINX_HTTPS_HOST_PORT}:443"
      - "${NGINX_LARAVEL_PORT}:31180"
      - "${NGINX_CCHOUSE_PORT}:21180"
      - "${NGINX_FRONT_PORT}:41180"
      - "${NGINX_XHPROF_PORT}:51180"
    volumes:
      - ${SOURCE_DIR}:/var/www/html/:rw
      - ${NGINX_CONFD_DIR}:/etc/nginx/conf.d/:rw
      - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:ro
      - ${NGINX_LOG_DIR}:/var/log/nginx/:rw
    restart: always
    networks:
      dnmp:
        ipv4_address: 172.30.0.5

  php72:
    build:
      context: .
      args:
        PHP_VERSION: ${PHP72_VERSION}
        ALPINE_REPOSITORIES: ${ALPINE_REPOSITORIES}
        PHP_EXTENSIONS: ${PHP72_EXTENSIONS}
        MORE_EXTENSION_INSTALLER: php72.sh
    volumes:
      - ${SOURCE_DIR}:/var/www/html/:rw
      - ${PHP72_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
      - ${PHP72_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
      - ${PHP72_LOG_DIR}:/var/log/php
    restart: always
    cap_add:
      - SYS_PTRACE
    networks:
      dnmp:
        ipv4_address: 172.30.0.6

  mysql:
    image: mysql:${MYSQL_VERSION}
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    volumes:
      - ${MYSQL_CONF_FILE}:/etc/mysql/conf.d/mysql.cnf:ro
      - ${MYSQL_DATA_DIR}:/var/lib/mysql/:rw
    restart: always
    networks:
      dnmp:
        ipv4_address: 172.30.0.7
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"

  redis:
    image: redis:${REDIS_VERSION}
    ports:
      - "${REDIS_HOST_PORT}:6379"
    volumes:
      - ${REDIS_CONF_FILE}:/etc/redis.conf:ro
    restart: always
    entrypoint: ["redis-server", "/etc/redis.conf"]
    networks:
      dnmp:
        ipv4_address: 172.30.0.8


#failed to connect to server [mongo:27017] docker 剛起來的時候 會有一小段時間連不到


  mongo:
    image: mongo:${MONGO_VERSION}
    ports:
      - "${MONGO_HOST_PORT}:27017"
    volumes:
      - ${MONGO_DATA_DB_DIR}:/data/db:rw
    restart: always
    networks:
      dnmp:
        ipv4_address: 172.30.0.9
    # external: true

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "${MONGO_EXPRESS_HOST_PORT}:8081"
    networks:
      dnmp:
        ipv4_address: 172.30.0.10



networks:
  dnmp:
    ipam:
      config:
        - subnet: 172.30.0.0/24
